### ISSUE TITLE
Linux 下无模型加载时一直报错 FileNotFoundError: [Errno 2] No such file or directory: 'weights/[]'

### ISSUE THREAD

**Issue by chenxvb** [liujing04/Retrieval-based-Voice-Conversion-WebUI#11]
OS: linux

python 执行 webui，功能正常，但会不停报错以下报文：

loading weights/[]
Traceback (most recent call last):
  File "/home/vior/miniconda3/envs/RVCtrain/lib/python3.9/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/vior/miniconda3/envs/RVCtrain/lib/python3.9/site-packages/gradio/blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "/home/vior/miniconda3/envs/RVCtrain/lib/python3.9/site-packages/gradio/blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/vior/miniconda3/envs/RVCtrain/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/vior/miniconda3/envs/RVCtrain/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/vior/miniconda3/envs/RVCtrain/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/E/AI/Mytts/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 167, in get_vc
    cpt = torch.load(person, map_location="cpu")
  File "/home/vior/miniconda3/envs/RVCtrain/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/vior/miniconda3/envs/RVCtrain/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/vior/miniconda3/envs/RVCtrain/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'weights/[]'

直到加载模型后解决，不知道能不能修复这个 bug

**Comment by liujing04** [comment]
训练完成后要刷新音色，选完音色才能正常加载

**Comment by chenxvb** [comment]
> 训练完成后要刷新音色，选完音色才能正常加载

这个知道，只是在初次启动一直到训练完成刷新后报错才会消失。并且错误会很快的塞满命令行，让训练和预处理的回显很难看到。或许你们可以在 readme 里面加一条要求加载初始模型之类的？

**Comment by chenxvb** [comment]
貌似是只要模型推理音色为空就会这样，哪怕 weight 目录下已有文件，只要在模型推理下的推理音色选择任何选项就不会报错了
