### ISSUE TITLE
Colab运行报错

### ISSUE THREAD

**Issue by Kira-Pgr** [liujing04/Retrieval-based-Voice-Conversion-WebUI#47]
环境: Google Colab
WebUI截图:
![image](https://user-images.githubusercontent.com/36188023/231711699-4f008ae4-5f25-432c-a481-dcf99f403c09.png)
![image](https://user-images.githubusercontent.com/36188023/231711779-60cd7f1d-e532-47cb-9aa2-102bbf0167f4.png)
数据集是一些3秒左右的音频切片(mp3格式)
> 不知道是不是我的数据集导致的问题，如果是这样的话请教一下怎么调整我的数据集qwq   

报错内容:
```
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 514, in <module>
    main()
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 42, in main
    mp.spawn(
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 150, in run
    train_and_evaluate(
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 195, in train_and_evaluate
    for batch_idx, info in enumerate(train_loader):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1326, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.9/dist-packages/torch/_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train/data_utils.py", line 306, in __getitem__
    return self.get_audio_text_pair(self.audiopaths_and_text[index])
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train/data_utils.py", line 248, in get_audio_text_pair
    phone = self.get_labels(phone)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train/data_utils.py", line 266, in get_labels
    phone = phone[:n_num, :]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```
日志:
```
/content/Retrieval-based-Voice-Conversion-WebUI
The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
Use Languane: en_US
2023-04-13 08:55:48.512021: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-13 08:55:49.817277: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-13 08:55:52 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://b2945b7454172d80c1.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
start preprocess
['trainset_preprocess_pipeline_print.py', '/content/drive/MyDrive/audiouploads', '40000', '2', '/content/Retrieval-based-Voice-Conversion-WebUI/logs/test', 'False']
/content/drive/MyDrive/audiouploads/dataset-1.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-11.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-14.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-16.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-18.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-2.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-21.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-23.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-25.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-27.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-29.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-30.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-32.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-35.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-37.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-39.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-40.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-42.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-44.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-46.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-48.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-6.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-8.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-10.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-13.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-15.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-17.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-19.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-20.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-22.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-24.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-26.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-28.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-3.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-31.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-34.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-36.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-38.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-4.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-41.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-43.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-45.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-47.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-5.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-7.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-9.mp3->Suc.
end preprocess

/content/drive/MyDrive/audiouploads/dataset-43.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-45.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-47.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-5.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-7.mp3->Suc.
/content/drive/MyDrive/audiouploads/dataset-9.mp3->Suc.
end preprocess

2023-04-13 08:57:22.578351: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-13 08:57:24 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
['extract_feature_print.py', 'cuda:0', '1', '0', '0', '/content/Retrieval-based-Voice-Conversion-WebUI/logs/test']
/content/Retrieval-based-Voice-Conversion-WebUI/logs/test
load model(s) from hubert_base.pt
2023-04-13 08:57:24 | INFO | fairseq.tasks.hubert_pretraining | current directory is /content/Retrieval-based-Voice-Conversion-WebUI
2023-04-13 08:57:24 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-04-13 08:57:24 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
move model to cuda:0
all-feature-47
now-47,all-0,0_0.wav,(136, 256)
now-47,all-4,13_0.wav,(49, 256)
now-47,all-8,16_0.wav,(98, 256)
now-47,all-12,1_0.wav,(66, 256)
now-47,all-16,23_0.wav,(90, 256)
now-47,all-20,27_0.wav,(104, 256)
now-47,all-24,30_0.wav,(154, 256)
now-47,all-28,34_0.wav,(107, 256)
now-47,all-32,38_0.wav,(149, 256)
now-47,all-36,41_0.wav,(89, 256)
now-47,all-40,45_0.wav,(63, 256)
now-47,all-44,7_0.wav,(88, 256)
all-feature-done
['extract_feature_print.py', 'cuda:0', '1', '0', '0', '/content/Retrieval-based-Voice-Conversion-WebUI/logs/test']
/content/Retrieval-based-Voice-Conversion-WebUI/logs/test
load model(s) from hubert_base.pt
move model to cuda:0
all-feature-47
now-47,all-0,0_0.wav,(136, 256)
now-47,all-4,13_0.wav,(49, 256)
now-47,all-8,16_0.wav,(98, 256)
now-47,all-12,1_0.wav,(66, 256)
now-47,all-16,23_0.wav,(90, 256)
now-47,all-20,27_0.wav,(104, 256)
now-47,all-24,30_0.wav,(154, 256)
now-47,all-28,34_0.wav,(107, 256)
now-47,all-32,38_0.wav,(149, 256)
now-47,all-36,41_0.wav,(89, 256)
now-47,all-40,45_0.wav,(63, 256)
now-47,all-44,7_0.wav,(88, 256)
all-feature-done
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-04-13 08:57:34.028941: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:jaxlib.mlir._mlir_libs:Initializing MLIR with module: _site_initialize_0
DEBUG:jaxlib.mlir._mlir_libs:Registering dialects from initializer <module 'jaxlib.mlir._mlir_libs._site_initialize_0' from '/usr/local/lib/python3.9/dist-packages/jaxlib/mlir/_mlir_libs/_site_initialize_0.so'>
DEBUG:jax._src.path:etils.epath found. Using etils.epath for file I/O.
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-04-13 08:57:38.841118: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:jaxlib.mlir._mlir_libs:Initializing MLIR with module: _site_initialize_0
DEBUG:jaxlib.mlir._mlir_libs:Registering dialects from initializer <module 'jaxlib.mlir._mlir_libs._site_initialize_0' from '/usr/local/lib/python3.9/dist-packages/jaxlib/mlir/_mlir_libs/_site_initialize_0.so'>
DEBUG:jax._src.path:etils.epath found. Using etils.epath for file I/O.
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
INFO:test:{'train': {'log_interval': 200, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 4, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 40000, 'filter_length': 2048, 'hop_length': 400, 'win_length': 2048, 'n_mel_channels': 125, 'mel_fmin': 0.0, 'mel_fmax': None, 'training_files': './logs/test/filelist.txt'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 10, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'use_spectral_norm': False, 'gin_channels': 256, 'spk_embed_dim': 109}, 'model_dir': './logs/test', 'experiment_dir': './logs/test', 'save_every_epoch': 5, 'name': 'test', 'total_epoch': 20, 'pretrainG': 'pretrained/G40k.pth', 'pretrainD': 'pretrained/D40k.pth', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 0, 'if_latest': 0, 'if_cache_data_in_gpu': 0}
WARNING:test:/content/Retrieval-based-Voice-Conversion-WebUI/train is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
gin_channels: 256 self.spk_embed_dim: 109
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 121, in run
    _, _, _, epoch_str = utils.load_checkpoint(utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d)  # D多半加载没事
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train/utils.py", line 163, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range
INFO:test:loaded pretrained pretrained/G40k.pth pretrained/D40k.pth
<All keys matched successfully>
<All keys matched successfully>
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-04-13 08:57:54.293283: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-13 08:57:54.299536: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-04-13 08:57:54.309187: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
2023-04-13 08:57:54.576913: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:jaxlib.mlir._mlir_libs:Initializing MLIR with module: _site_initialize_0
DEBUG:jaxlib.mlir._mlir_libs:Registering dialects from initializer <module 'jaxlib.mlir._mlir_libs._site_initialize_0' from '/usr/local/lib/python3.9/dist-packages/jaxlib/mlir/_mlir_libs/_site_initialize_0.so'>
DEBUG:jaxlib.mlir._mlir_libs:Initializing MLIR with module: _site_initialize_0
DEBUG:jaxlib.mlir._mlir_libs:Registering dialects from initializer <module 'jaxlib.mlir._mlir_libs._site_initialize_0' from '/usr/local/lib/python3.9/dist-packages/jaxlib/mlir/_mlir_libs/_site_initialize_0.so'>
DEBUG:jaxlib.mlir._mlir_libs:Initializing MLIR with module: _site_initialize_0
DEBUG:jaxlib.mlir._mlir_libs:Registering dialects from initializer <module 'jaxlib.mlir._mlir_libs._site_initialize_0' from '/usr/local/lib/python3.9/dist-packages/jaxlib/mlir/_mlir_libs/_site_initialize_0.so'>
DEBUG:jax._src.path:etils.epath found. Using etils.epath for file I/O.
DEBUG:jax._src.path:etils.epath found. Using etils.epath for file I/O.
DEBUG:jaxlib.mlir._mlir_libs:Initializing MLIR with module: _site_initialize_0
DEBUG:jaxlib.mlir._mlir_libs:Registering dialects from initializer <module 'jaxlib.mlir._mlir_libs._site_initialize_0' from '/usr/local/lib/python3.9/dist-packages/jaxlib/mlir/_mlir_libs/_site_initialize_0.so'>
DEBUG:jax._src.path:etils.epath found. Using etils.epath for file I/O.
DEBUG:jax._src.path:etils.epath found. Using etils.epath for file I/O.
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
/usr/local/lib/python3.9/dist-packages/torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:862.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/usr/local/lib/python3.9/dist-packages/torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:862.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/usr/local/lib/python3.9/dist-packages/torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:862.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/usr/local/lib/python3.9/dist-packages/torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:862.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/content/Retrieval-based-Voice-Conversion-WebUI/train/mel_processing.py:93: FutureWarning: Pass sr=40000, n_fft=2048, n_mels=125, fmin=0.0, fmax=None as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel = librosa_mel_fn(sampling_rate, n_fft, num_mels, fmin, fmax)
/usr/local/lib/python3.9/dist-packages/torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:862.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
/usr/local/lib/python3.9/dist-packages/torch/autograd/__init__.py:200: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 21, 96], strides() = [43296, 96, 1]
bucket_view.sizes() = [1, 21, 96], strides() = [2016, 96, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:323.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:test:Train Epoch: 1 [0%]
INFO:test:[0, 0.0001]
INFO:test:loss_disc=3.231, loss_gen=2.107, loss_fm=9.420,loss_mel=30.646, loss_kl=5.000
DEBUG:matplotlib:matplotlib data path: /usr/local/lib/python3.9/dist-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/root/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 514, in <module>
    main()
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 42, in main
    mp.spawn(
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 150, in run
    train_and_evaluate(
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 195, in train_and_evaluate
    for batch_idx, info in enumerate(train_loader):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1326, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.9/dist-packages/torch/_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train/data_utils.py", line 306, in __getitem__
    return self.get_audio_text_pair(self.audiopaths_and_text[index])
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train/data_utils.py", line 248, in get_audio_text_pair
    phone = self.get_labels(phone)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train/data_utils.py", line 266, in get_labels
    phone = phone[:n_num, :]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by liujing04** [comment]
确保logs/mute文件夹下有东西（和github上一样）

**Comment by liujing04** [comment]
@fumiama 看看？

**Comment by fumiama** [comment]
我不知道，没遇到过这种错

**Comment by Kira-Pgr** [comment]
> 确保logs/mute文件夹下有东西（和github上一样）

我记得是有东西的qwq

**Comment by Kira-Pgr** [comment]
https://drive.google.com/drive/folders/1QaxW3z1jdFsjr96XZKg2blU9qNMOotbM?usp=sharing   这是我的数据集

**Comment by liujing04** [comment]
@Kira-Pgr 已修复，更新了有问题的infer-web.py，你看看怎么同步到你那。
