### ISSUE TITLE
步骤0加载不到音频提示File Not Found

### ISSUE THREAD

**Issue by MagicGJ** [liujing04/Retrieval-based-Voice-Conversion-WebUI#98]
```
Use Language: zh_CN
Running on local URL:  http://0.0.0.0:7865
start preprocess
['trainset_preprocess_pipeline_print.py', 'E:\\BaiduYunDownload\\ayakaVoice', '40000', '12', 'E:\\PycharmProjects\\Retrieval-based-Voice-Conversion-WebUI/logs/test', 'False']
E:\BaiduYunDownload\ayakaVoice/1.wav->Traceback (most recent call last):
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\.venv\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\.venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "e:\anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "e:\anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\trainset_preprocess_pipeline_print.py", line 73, in pipeline
    audio = load_audio(path, self.sr)
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] 系统找不到指定的文件。

E:\BaiduYunDownload\ayakaVoice/20.wav->Traceback (most recent call last):
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\.venv\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\.venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "e:\anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "e:\anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\trainset_preprocess_pipeline_print.py", line 73, in pipeline
    audio = load_audio(path, self.sr)
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] 系统找不到指定的文件。

.........以下省略
```

一开始以为是我带了中文路径，但是把名字改了之后似乎还是不行..

**Comment by liujing04** [comment]
我应该如何复现你的bug？

**Comment by OedoSoldier** [comment]
安装FFMPEG

**Comment by MagicGJ** [comment]
> 安装FFMPEG

确实是FFMPEG问题，重装了一下就好了，谢谢

**Comment by iielse** [comment]
> > 安装FFMPEG
> 
> 确实是FFMPEG问题，重装了一下就好了，谢谢

这句话能细说操作步骤吗？谢谢
