### ISSUE TITLE
训练结束后报错

### ISSUE THREAD

**Issue by IceWind233** [liujing04/Retrieval-based-Voice-Conversion-WebUI#99]
训练结束生成模型文件但是报错
`
Traceback (most recent call last):
  File "train_nsf_sim_cache_sid_load_pretrain.py", line 684, in <module>
    main()
  File "train_nsf_sim_cache_sid_load_pretrain.py", line 50, in main
    mp.spawn(
  File "E:\User\Voice\VoiceEnv\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "E:\User\Voice\VoiceEnv\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "E:\User\Voice\VoiceEnv\lib\site-packages\torch\multiprocessing\spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 2333333
`

**Comment by liujing04** [comment]
You have successfully trained the model.

**Comment by IceWind233** [comment]
但是兄弟，他没有生成index和npy文件：3

**Comment by IceWind233** [comment]
问题不是很大是我没下hubert_base
